### ISSUE TITLE
Wotlk-AI Compile error

### ISSUE THREAD

**Issue by Talmeron** [tkrokli/TrinityCore#12]
Error	1	error C1083: Cannot open include file: 'format.h': No such file or directory	C:\tribots\src\server\shared\Utilities\StringFormat.h	22	1	plugins

Which of course gives: Error	2	error LNK1181: cannot open input file '..\..\plugins\Release\plugins.lib'	C:\tribots\build\src\server\worldserver\LINK	worldserver

**Comment by Talmeron** [comment]
>C:\tribots\src\server\shared\Utilities\StringFormat.h(22): fatal error C1083: Cannot open include file: 'format.h': No such file or directory

**Comment by tkrokli** [comment]
1. This looks like a MySQL error. In that case, you need to update your MySQL installation.
2. You have not told me anything about which source you are using. That is vital information.
3. Provide information about your OS architecture (x86 (Win32) or x64(Win64) and such).
4. Please also include your version of Git Extensions, MySQL, Visual Studio, OpenSSL etc.

**Comment by Talmeron** [comment]
Normal Trinity compiles with no error. 

Win 32(8)
Mysql 5.6.17
OpenSSL 1.0.2c
Git Extension 2.48.15
Visual Studio 2013 Community

**Comment by tkrokli** [comment]
OK, I will test compiling it myself to see what happens and if I can replicate your issue.

**Comment by Talmeron** [comment]
Ah....I did. trinity-wotlk-ai (I assume lfg? But there is no branch by that name.) Just trinity-wotlk-ai

**Comment by tkrokli** [comment]
You are correct. I just noticed that I renamed it locally on my computer, but not here on github.com

**Comment by tkrokli** [comment]
I checked the file StringFormat.h and found that it is identical to the TrinityCore file. Therefore it looks like VS2013 is unable to tell what actually precludes and causes this error. I need to Google this error now.

**Comment by tkrokli** [comment]
After some searching, I have found out that the entire folder https://github.com/tkrokli/TrinityCore/tree/trinity-wotlk-ai/dep/cppformat with contents as well as the file /src/server/shared/Utilities/StringFormat.h was added to the TrinityCore 3.3.5 source for the first time 18 March 2015, 02:59 CET in commit https://github.com/TrinityCore/TrinityCore/commit/03176662d10d6068df035b355eb4c47ddd4e1dde (cherry picked from commit https://github.com/TrinityCore/TrinityCore/commit/cc0c9add5a3f3a17e19029ddcaa7e711040f4fc5 in the 6.x branch).

This happened of course after the latest working merge in ike3's own repository, where the TrinityCore 3.3.5 source was merged 10 March 2015, 04:34 CET - commit https://github.com/ike3/mangosbot/commit/f9fcae489348e354a11bbc02211c60185e1d3bca with 10,639 additions and 1,878 deletions compared to the previous merge https://github.com/ike3/mangosbot/commit/cfcf38602b9bc13d48aa5a1927523cf7573e1b07 on 10. November 2014.

As I see it, we have got only 2 options here.
A) Use ike3's own source https://github.com/ike3/mangosbot (default branch: trinity-wotlk-ai)
B) Find out how to fix the issue introduced by https://github.com/TrinityCore/TrinityCore/commit/03176662d10d6068df035b355eb4c47ddd4e1dde

I don't know which option you will go for, but the quickest solution will be to use a working source (A).

**Comment by tkrokli** [comment]
Even though I got past the error by copying the file /dep/cppformat/format.h to the same folder as StringFormat.h , I got 5 new errors in the PlayerbotAI files:
```
Error    2    error C2039: 'questItems'           : is not a member of 'GameObjectTemplate'    C:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\LootObjectStack.cpp    89    1    plugins
Error    5    error C2039: 'GetGlobalCooldownMgr' : is not a member of 'Player'                C:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\PlayerbotAI.cpp       379    1    plugins
Error    6    error C2228: left of '.HasGlobalCooldown' must have class/struct/union           C:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\PlayerbotAI.cpp       379    1    plugins
Error    8    error C2039: 'HasSpellCooldown'     : is not a member of 'Player'                C:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\PlayerbotAI.cpp       822    1    plugins
Error   59    error LNK1181: cannot open input file '..\..\plugins\Release\plugins.lib'        C:\Build\trinity-wotlk-ai-lfg-transmog_x64\src\server\worldserver\LINK                         worldserver
        60    IntelliSense: class "GameObjectTemplate" has no member "questItems"              c:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\LootObjectStack.cpp    89   34    plugins
        61    IntelliSense: namespace "std"            has no member "vector"                  c:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\playerbot.h             3    6    plugins
        62    IntelliSense: expected a ';'                                                     c:\github.com\tkrokli\trinity-wotlk-ai\src\plugins\playerbot\playerbot.h             3   12    plugins
```
I don't feel very motivated to fix these errors, so I will return to the ike3 trinity-wotlk-ai source from March.

**Comment by tkrokli** [comment]
I saw no other way than to reset the branch back to ike3's original with only the Feyzee LFG fix added.

This issue is thereby solved like Alexander the great solved The Gordian Knot.
